export const datosPreguntas = [
    {
        ID_Pregunta: '1',
        ID_usuario: '123',
        textoPregunta: "¿Cómo se realiza la busqueda de ingredientes?",
        type: "P",
        respuesta: null,
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '2',
        ID_usuario: '456',
        textoPregunta: "¿Como puedo agregar mi receta?",
        type: "P",
        respuesta: null,
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '3',
        ID_usuario: '789',
        textoPregunta: "Deberian agregar mas recetas",
        type: "S",
        respuesta: null,
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '4',
        ID_usuario: '101112',
        textoPregunta: "Pueden añadir strudel",
        type: "S",
        respuesta: null,
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '5',
        ID_usuario: '131415',
        textoPregunta: "¿Cómo se agrega una receta?",
        type: "P",
        respuesta: null,
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '6',
        ID_usuario: '161718',
        textoPregunta: "Pongan pasta a los ingredientes",
        type: "S",
        respuesta: null,
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '7',
        ID_usuario: '192021',
        textoPregunta: "¿Cómo se realiza la busqueda de recetas?",
        type: "P",
        respuesta: 'Seleccione los ingredientes requeridos y automaticamente se realiza la consulta.',
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '8',
        ID_usuario: '222324',
        textoPregunta: "¿Cómo se realiza la busqueda de ingredientes?",
        type: "P",
        respuesta: 'Escriba el nombre del ingrediente y se realizará la busqueda en la base de datos de ingredientes.',
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '8',
        ID_usuario: '222324',
        textoPregunta: "¿Cómo se realiza la busqueda de ingredientes?",
        type: "P",
        respuesta: 'Escriba el nombre del ingrediente y se realizará la busqueda en la base de datos de ingredientes.',
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '8',
        ID_usuario: '222324',
        textoPregunta: "¿Cómo se realiza la busqueda de ingredientes?",
        type: "P",
        respuesta: 'Escriba el nombre del ingrediente y se realizará la busqueda en la base de datos de ingredientes.',
        userName: "jcarrenoar@unal.edu.co",
    },
    {
        ID_Pregunta: '8',
        ID_usuario: '222324',
        textoPregunta: "¿Cómo se realiza la busqueda de ingredientes?",
        type: "P",
        respuesta: 'Escriba el nombre del ingrediente y se realizará la busqueda en la base de datos de ingredientes.',
        userName: "jcarrenoar@unal.edu.co",
    },
]